apiVersion: v1
# 자원의 종류
kind: Pod
metadata:
# pod의 이름은 네임스페이스에서 유일해야함
  name: nginx-my-nginx1
  namespace: rim  # 네임스페이스 지정시, 여기에 지정
  # labels는 service의 라우팅 대상이 되는 기준.
  # 같은 label이 붙은 여러개의 pod생성 가능.
  labels:
    app: my-nginx
spec:
# 이거 전체 복제해서 컨테이너 여러개 할 수 있다
  containers:
  # name안중요함-아무거나
  - name: nginx
  # 이미지 개중요함-정확하게
    image: nginx
# 버전 안쓰면 latest 
# pod의 포트는 내부 포트를 의미하고, 프로그램 자체의 포트와 동일 (외부포트x)
    ports:
    - containerPort: 80