
server:
#  port번호가 0번일 경우, 0~65535중에 현재 host에서 사용하지 않는 port임의로 설정
  port: 0

#  유레카 주소설정
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

spring:
#  추가
  config:
    activate:
      on-profile: local
  application:
    name: member-service
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/ordermsa
    username: root
    password: test1234
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MariaDBDialect
    generate-ddl: true
    hibernate:
      ddl-auto: create
    show_sql: true

  redis:
    host: localhost
    port: 6379
    #  스프링 안에 봍통 넣는다


mybatis:
  mapper-locations: classpath:/mapper/**/*.xml


jwt:
  secretKey: YmV5b25kYWNjZXNzdG9rZW5zZWNyZXRrZXliZXlvbmRhY2Nlc3N0b2tlbnNlY3JldGtleWJleW9uZGFjY2Vzc3Rva2Vuc2VjcmV0a2V5
  expiration: 30
#  Rt시간만 바꿔서 설정
  secretKeyRt: YmV5b25kYWNjZXNzdG9rZW5zZWNyZXRrZXliZXlvbmRhY2Nlc3N0b2tlbnNlY3JldGtleWJleW9uZGFjY2Vzc3Rva2Vuc2VjcmV0a2V5
  expirationRt: 3000

logging:
  level:
    root: info


