apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: my-issuer
  namespace: rim
spec:
  acme:
  # ca 서버 주소. 해당 서버를 통해 인증서 발행
    server: https://acme-v02.api.letsencrypt.org/directory
  # 인증서 만료 또는 갱신 필요시 알람 email
    email: sssurim@gmail.com
    privateKeySecretRef:
    # 인증서를 발급받기 위해 ca와 통신시에 사용되는 Secret 이름(중요X)
      name: my-issuer
    solvers:
    - http01:
        ingress:
        # 도메인의 소유권을 확인하기 위해 cert-manager는 nginx기반의 ingress controller를 활용해 검증한다는 의미
          class: nginx
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
# name은 크게 중요하지는 않다
  name: server-rim2379-store-tls
  namespace: rim
spec:
# cert-manager가 아래 secretName에서 지정한 이름으로 Secret을 생성 //이름 일치만 시키기
  secretName: server-rim2379-store-tls
  duration: 2160h #90day
  renewBefore: 360h #before 15day
  issuerRef:
  # ClusterIssuer의 이름을 참조
    name: my-issuer
    kind: ClusterIssuer
    # 중요. 실제 도메인명
  commonName: server.rim2379.store
  dnsNames:
  # 추가적인 서브도메인을 추가하고 싶은경우에 여기에 나열 //추가할거면 (ex.모니터링) 도메인 추가
  - server.rim2379.store